version: '3'
services:
  todoback:
    build: todobackend
    ports:
      - 3001:3001
  todofront:
    build: todofrontend
    depends_on:
      - todoback
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
  todotests:
    build: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
